#!/usr/bin/env bash
set -euo pipefail

# Cores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_ok() { echo -e "${GREEN}[OK]${NC} $1"; }

TEST_FILE="packages/analysis-agent/src/agent.test.ts"

log_info "Reescrevendo testes do Agente com Mocks Inteligentes (Context-Aware)..."

cat > "$TEST_FILE" << 'EOF'
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { AnalysisAgent } from './agent';

// 1. Hoisting
const mocks = vi.hoisted(() => {
  return {
    generateJSON: vi.fn(),
    generateText: vi.fn()
  };
});

// 2. Mock do Módulo
vi.mock('./services/llm/llm-service', () => {
  return {
    LLMService: vi.fn().mockImplementation(() => ({
      generateJSON: mocks.generateJSON,
      generateText: mocks.generateText
    }))
  };
});

describe('AnalysisAgent (Orchestration)', () => {
  let agent: AnalysisAgent;

  beforeEach(() => {
    vi.clearAllMocks();
    agent = new AnalysisAgent('test-key');
  });

  /**
   * Helper para configurar mocks inteligentes baseados no conteúdo do System Prompt.
   * Isso torna o teste resiliente à ordem de execução.
   */
  const setupContextAwareMocks = (scenario: 'CHAT' | 'PROJECT') => {
    
    // Mock para Chat (Texto Livre)
    mocks.generateText.mockImplementation(async (sys: string) => {
      return "Resposta do Chat Mockada";
    });

    // Mock para JSON (Estruturado)
    mocks.generateJSON.mockImplementation(async (sys: string, user: string) => {
      const prompt = sys.toLowerCase();

      // 1. Router de Intenção
      if (prompt.includes("classifique a intenção")) {
        if (scenario === 'CHAT') return JSON.stringify({ type: "QUESTION", reasoning: "Dúvida" });
        return JSON.stringify({ type: "NEW_PROJECT", reasoning: "Novo projeto" });
      }

      // 2. Analista
      if (prompt.includes("analista")) {
        return JSON.stringify({ 
          summary: "Resumo do Projeto Teste", 
          complexity: "Baixa", 
          assumptions: ["Assumption A"] 
        });
      }

      // 3. Produto (PO)
      if (prompt.includes("product owner") || prompt.includes("po técnico")) {
        if (prompt.includes("detalhe hus")) {
           // HUs Detalhadas
           return JSON.stringify({ 
             userStories: [{ 
               id: "HU-001", title: "Test HU", priority: "P1", role: "Dev", action: "Test", benefit: "Quality", 
               acceptanceCriteria: [], functionalRequirements: [], securityRequirements: [] 
             }] 
           });
        }
        // Épicos
        return JSON.stringify({ 
          epics: [{ title: "Epic 1", context: "Ctx", requirements: ["Req 1"] }] 
        });
      }

      // 4. Arquiteto
      if (prompt.includes("arquiteto")) {
        return JSON.stringify({ 
          stack: "Node/React", 
          // Retorna um arquivo customizado para validar que o pipeline o processou
          manifest: [{ path: "custom.ts", purpose: "Custom Logic", criticality: "Core" }] 
        });
      }

      // 5. Engenheiro (Dev) - Geração de Código
      if (prompt.includes("dev sênior") || prompt.includes("codifique")) {
        // O prompt contém o arquivo alvo no formato "Implemente {path}"
        let path = "unknown.ts";
        if (sys.includes("Implemente ")) {
            path = sys.split("Implemente ")[1].split(".")[0] + ".ts"; // Extração simples
        }
        return JSON.stringify({ 
          path: path, 
          code: "// Code generated by mock", 
          explanation: "Mocked" 
        });
      }

      // Fallback seguro
      return "{}";
    });
  };

  it('deve detectar intenção de PERGUNTA e retornar resposta de chat', async () => {
    setupContextAwareMocks('CHAT');

    const result: any = await agent.analyze("Como isso funciona?", { files: [] });

    expect(result.summary).toBe("Resposta do Chat Mockada");
    expect(result.fenix.notes).toBe("Chat Response");
    // O array de arquivos deve vir vazio no modo chat
    expect(result.engine.files).toHaveLength(0);
  });

  it('deve orquestrar o pipeline completo para NOVOS PROJETOS', async () => {
    setupContextAwareMocks('PROJECT');

    const result: any = await agent.analyze("Crie um app", { files: [] });

    // Validações de Estrutura
    
    // 1. Resumo do Analista
    expect(result.summary).toBe("Resumo do Projeto Teste");

    // 2. Arquivos Gerados
    // O TemplateEngine (v8.0) injeta automaticamente 5 arquivos base (package.json, etc)
    // + 1 arquivo customizado do Arquiteto Mockado (custom.ts)
    // Total esperado >= 6
    expect(result.engine.files.length).toBeGreaterThanOrEqual(5);
    
    // Verifica se o arquivo customizado da IA chegou no final
    const customFile = result.engine.files.find((f: any) => f.path.includes("custom"));
    expect(customFile).toBeDefined();
    expect(customFile.code).toBe("// Code generated by mock");

    // 3. HUs
    expect(result.product.userStories).toHaveLength(1);
    expect(result.product.userStories[0].title).toBe("Test HU");
  });
});
EOF

log_ok "Testes blindados com Context-Aware Mocking."

# Rodar teste
log_info "Validando nova suite de testes..."
if pnpm --filter @mini-ide/analysis-agent test; then
    log_ok "SUCESSO: Testes passaram de forma robusta."
else
    echo "FALHA: Testes ainda com erro."
    exit 1
fi

# Pipeline Final
bash ./42_pipeline_checklist.sh
